basePath: /
definitions:
  entity.SecretQuestion:
    properties:
      id:
        type: string
      question:
        type: string
    type: object
  v1.errResponse:
    properties:
      error:
        type: string
    type: object
  v1.registerRequestDTO:
    properties:
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      secretQuestionAnswer:
        type: string
      secretQuestionID:
        type: string
    type: object
  v1.secretQuestionsResponseDTO:
    properties:
      questions:
        items:
          $ref: '#/definitions/entity.SecretQuestion'
        type: array
    type: object
host: localhost:9000
info:
  contact: {}
  description: API for auth microservice
  version: "1.0"
paths:
  /v1/questions:
    get:
      consumes:
      - application/json
      description: Get all secret questions
      operationId: get-question
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.secretQuestionsResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errResponse'
      summary: GetQuestions
      tags:
      - questions
  /v1/register:
    post:
      consumes:
      - application/json
      description: Register new user
      operationId: register-user
      parameters:
      - description: Enter info user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.registerRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.errResponse'
      summary: Register
      tags:
      - register
swagger: "2.0"
